export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GOT_PRODUCT_LIST = "GOT_PRODUCT_LIST";
export const FAILED_PRODUCT_LIST = "FAILED_PRODUCT_LIST";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GOT_PRODUCT_DETAIL = "GOT_PRODUCT_DETAIL";
export const FAILED_PRODUCT_DETAIL = "FAILED_PRODUCT_DETAIL";
